M48
; DRILL file {KiCad 7.0.7} date Sun Sep 10 19:25:55 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-10T19:25:55-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X175.855Y-105.22
T2
X175.07Y-41.275
T0
M30
