M48
; DRILL file {KiCad 7.0.6} date Tue Aug 15 13:49:35 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-15T13:49:35-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X174.353Y-89.635
T2
X133.828Y-25.4
T0
M30
